#!/usr/bin/env bash

# This script changes localhost and facebook.com IP addresses

# Overwrite /etc/hosts with new values
echo "127.0.0.2 localhost" > /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts